In [43]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# I. Clean WB WDI dataset

In [44]:
df = pd.read_csv("WB_Extracted_WDI_Data.csv")
df

,Country Name,Country Code,Series Name,Series Code,2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024],2025 [YR2025]
0,Brunei Darussalam,BRN,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,7.41473381939997,7.47961376576273,7.56922294285959,..,..
1,Brunei Darussalam,BRN,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,9.9862,9.5371,9.7036,9.3667,..
2,Brunei Darussalam,BRN,Carbon dioxide (CO2) emissions from Industrial...,EN.GHG.CO2.IP.MT.CE.AR5,0.1097,0.1303,0.1301,0.1316,..
3,Brunei Darussalam,BRN,Population density (people per sq. km of land ...,EN.POP.DNST,85.715559772296,86.4079696394687,87.0870967741936,87.8028462998102,..
4,Brunei Darussalam,BRN,Urban land area (sq. km),AG.LND.TOTL.UR.K2,..,..,..,..,..
...,...,...,...,...,...,...,...,...,...
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,Data from database: World Development Indicators,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,Last Updated: 10/08/2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [45]:
df.columns

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]', '2024 [YR2024]',
       '2025 [YR2025]'],
      dtype='object')

In [46]:
# change ".." to nan
df.replace("..", np.nan, inplace=True)
df.isnull().sum()

Country Name      3
Country Code      5
Series Name       5
Series Code       5
2021 [YR2021]    16
2022 [YR2022]    16
2023 [YR2023]    16
2024 [YR2024]    27
2025 [YR2025]    71
dtype: int64

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 82 entries, 0 to 81
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   79 non-null     object
 1   Country Code   77 non-null     object
 2   Series Name    77 non-null     object
 3   Series Code    77 non-null     object
 4   2021 [YR2021]  66 non-null     object
 5   2022 [YR2022]  66 non-null     object
 6   2023 [YR2023]  66 non-null     object
 7   2024 [YR2024]  55 non-null     object
 8   2025 [YR2025]  11 non-null     object
dtypes: object(9)
memory usage: 5.9+ KB

In [48]:
# drop columns with empty rows
df_clean = df.dropna(subset=['Series Code'])

In [49]:
# reshape from wide to long format
year_cols = ['2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]', '2024 [YR2024]', '2025 [YR2025]']
df_clean = df_clean.melt(
    id_vars=['Country Name', 'Country Code', 'Series Name', 'Series Code'],
    value_vars=year_cols,
    var_name='Year',
    value_name='Value'
)

In [50]:
# clean year column
df_clean['Year'] = df_clean['Year'].str.split(' ').str[0].astype(int)
df_clean['Value'] = pd.to_numeric(df_clean['Value'], errors='coerce')

In [51]:
# round off values in value column
df_clean['Value'] = df_clean['Value'].round(2)
df_clean.head()

,Country Name,Country Code,Series Name,Series Code,Year,Value
0,Brunei Darussalam,BRN,"PM2.5 air pollution, mean annual exposure (mic...",EN.ATM.PM25.MC.M3,2021,7.41
1,Brunei Darussalam,BRN,Carbon dioxide (CO2) emissions (total) excludi...,EN.GHG.CO2.MT.CE.AR5,2021,9.99
2,Brunei Darussalam,BRN,Carbon dioxide (CO2) emissions from Industrial...,EN.GHG.CO2.IP.MT.CE.AR5,2021,0.11
3,Brunei Darussalam,BRN,Population density (people per sq. km of land ...,EN.POP.DNST,2021,85.72
4,Brunei Darussalam,BRN,Urban land area (sq. km),AG.LND.TOTL.UR.K2,2021,NaN

In [52]:
# save current dataset
df_clean.to_csv("WB_WDI_Cleaned.csv", index=False)

# II. Clean (another dataset)

# III. Merge all datasets